FROM python:3.11-slim

WORKDIR /app

# Copy the requirements.txt file
COPY ./requirements.txt /app/requirements.txt

# Install the package dependencies in the generated requirements.txt file.
RUN pip install -r /app/requirements.txt

# Entrypoint to keep container running
ENTRYPOINT ["tail", "-f", "/dev/null"]
