FROM python:3.11-slim

WORKDIR /project

# Copy the requirements.txt file
COPY ./requirements.txt /project/requirements.txt

# Install the package dependencies in the generated requirements.txt file.
RUN pip install -r /project/requirements.txt

# Add project's dir in PYTHONPATH
ENV PYTHONPATH=/project:$PYTHONPATH

# Entrypoint to keep container running
ENTRYPOINT ["tail", "-f", "/dev/null"]
