# Usa la imagen base de Jupyter
FROM jupyter/base-notebook:latest

USER root

WORKDIR /home/jovyan

COPY ./requirements.txt /home/jovyan/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

RUN chown -R jovyan:users /home/jovyan

# Add project's dir in PYTHONPATH
ENV PYTHONPATH=/home/jovyan:$PYTHONPATH

USER jovyan

# Unable token auth
CMD ["start-notebook.sh", "--NotebookApp.token=''"]
